#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrgaEnhance.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DATA_ABS1")]
	public partial class LtsAbsenDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertlembarkerja(lembarkerja instance);
    partial void Updatelembarkerja(lembarkerja instance);
    partial void Deletelembarkerja(lembarkerja instance);
    partial void Inserttblinjekdept1(tblinjekdept1 instance);
    partial void Updatetblinjekdept1(tblinjekdept1 instance);
    partial void Deletetblinjekdept1(tblinjekdept1 instance);
    #endregion
		
		public LtsAbsenDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DATA_ABS1ConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LtsAbsenDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LtsAbsenDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LtsAbsenDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LtsAbsenDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<lembarkerja> lembarkerjas
		{
			get
			{
				return this.GetTable<lembarkerja>();
			}
		}
		
		public System.Data.Linq.Table<lembarkerja_temp_new> lembarkerja_temp_news
		{
			get
			{
				return this.GetTable<lembarkerja_temp_new>();
			}
		}
		
		public System.Data.Linq.Table<AbsentCode> AbsentCodes
		{
			get
			{
				return this.GetTable<AbsentCode>();
			}
		}
		
		public System.Data.Linq.Table<VW_M_INJEK_DEPT_ALL> VW_M_INJEK_DEPT_ALLs
		{
			get
			{
				return this.GetTable<VW_M_INJEK_DEPT_ALL>();
			}
		}
		
		public System.Data.Linq.Table<tblinjekdept1> tblinjekdept1s
		{
			get
			{
				return this.GetTable<tblinjekdept1>();
			}
		}
		
		public System.Data.Linq.Table<lembarkerja_BACKUP> lembarkerja_BACKUPs
		{
			get
			{
				return this.GetTable<lembarkerja_BACKUP>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ABSENSI_ONLINE")]
		public int SP_ABSENSI_ONLINE()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_UploadDataAbsenPama")]
		public int cusp_UploadDataAbsenPama([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sSession, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sNrp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sSession, sNrp);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lembarkerja")]
	public partial class lembarkerja : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private string _nrp;
		
		private System.Nullable<System.DateTime> _tanggal;
		
		private string _shift;
		
		private string _cn_unit;
		
		private string _Alat;
		
		private System.Nullable<double> _jk;
		
		private System.Nullable<double> _jkp_opr;
		
		private System.Nullable<double> _rest_time;
		
		private string _Absent;
		
		private System.Nullable<decimal> _PemotongUlap;
		
		private string _TingkatSP;
		
		private System.Nullable<System.DateTime> _in;
		
		private System.Nullable<System.DateTime> _out;
		
		private System.Nullable<double> _jk1;
		
		private System.Nullable<decimal> _RosterCode;
		
		private string _NoMesin1;
		
		private string _NoMesin2;
		
		private System.Nullable<System.DateTime> _Terlambat;
		
		private System.Nullable<double> _SKL;
		
		private System.Nullable<double> _SKL2;
		
		private System.Nullable<double> _SKL3;
		
		private System.Nullable<double> _SKL1;
		
		private string _InputBY;
		
		private System.Nullable<System.DateTime> _TGLINPUT;
		
		private System.Nullable<System.DateTime> _IpoUpdateTime;
		
		private string _alat_follow_up;
		
		private string _Follow_Up;
		
		private string _Progress;
		
		private System.Nullable<bool> _Problem;
		
		private string _alat_approve_status;
		
		private string _Ket_Lembur;
		
		private System.Nullable<bool> _Aprove_Atasan;
		
		private string _Aprove_by;
		
		private System.Nullable<System.DateTime> _Aprove_tanggal;
		
		private System.Nullable<bool> _Aprove_HC;
		
		private string _Aprove_HC_by;
		
		private System.Nullable<System.DateTime> _Aprove_HC_tanggal;
		
		private string _Tindakan;
		
		private System.Nullable<System.DateTime> _Tgl_Tindakan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnnrpChanging(string value);
    partial void OnnrpChanged();
    partial void OntanggalChanging(System.Nullable<System.DateTime> value);
    partial void OntanggalChanged();
    partial void OnshiftChanging(string value);
    partial void OnshiftChanged();
    partial void Oncn_unitChanging(string value);
    partial void Oncn_unitChanged();
    partial void OnAlatChanging(string value);
    partial void OnAlatChanged();
    partial void OnjkChanging(System.Nullable<double> value);
    partial void OnjkChanged();
    partial void Onjkp_oprChanging(System.Nullable<double> value);
    partial void Onjkp_oprChanged();
    partial void Onrest_timeChanging(System.Nullable<double> value);
    partial void Onrest_timeChanged();
    partial void OnAbsentChanging(string value);
    partial void OnAbsentChanged();
    partial void OnPemotongUlapChanging(System.Nullable<decimal> value);
    partial void OnPemotongUlapChanged();
    partial void OnTingkatSPChanging(string value);
    partial void OnTingkatSPChanged();
    partial void OninChanging(System.Nullable<System.DateTime> value);
    partial void OninChanged();
    partial void OnoutChanging(System.Nullable<System.DateTime> value);
    partial void OnoutChanged();
    partial void Onjk1Changing(System.Nullable<double> value);
    partial void Onjk1Changed();
    partial void OnRosterCodeChanging(System.Nullable<decimal> value);
    partial void OnRosterCodeChanged();
    partial void OnNoMesin1Changing(string value);
    partial void OnNoMesin1Changed();
    partial void OnNoMesin2Changing(string value);
    partial void OnNoMesin2Changed();
    partial void OnTerlambatChanging(System.Nullable<System.DateTime> value);
    partial void OnTerlambatChanged();
    partial void OnSKLChanging(System.Nullable<double> value);
    partial void OnSKLChanged();
    partial void OnSKL2Changing(System.Nullable<double> value);
    partial void OnSKL2Changed();
    partial void OnSKL3Changing(System.Nullable<double> value);
    partial void OnSKL3Changed();
    partial void OnSKL1Changing(System.Nullable<double> value);
    partial void OnSKL1Changed();
    partial void OnInputBYChanging(string value);
    partial void OnInputBYChanged();
    partial void OnTGLINPUTChanging(System.Nullable<System.DateTime> value);
    partial void OnTGLINPUTChanged();
    partial void OnIpoUpdateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnIpoUpdateTimeChanged();
    partial void Onalat_follow_upChanging(string value);
    partial void Onalat_follow_upChanged();
    partial void OnFollow_UpChanging(string value);
    partial void OnFollow_UpChanged();
    partial void OnProgressChanging(string value);
    partial void OnProgressChanged();
    partial void OnProblemChanging(System.Nullable<bool> value);
    partial void OnProblemChanged();
    partial void Onalat_approve_statusChanging(string value);
    partial void Onalat_approve_statusChanged();
    partial void OnKet_LemburChanging(string value);
    partial void OnKet_LemburChanged();
    partial void OnAprove_AtasanChanging(System.Nullable<bool> value);
    partial void OnAprove_AtasanChanged();
    partial void OnAprove_byChanging(string value);
    partial void OnAprove_byChanged();
    partial void OnAprove_tanggalChanging(System.Nullable<System.DateTime> value);
    partial void OnAprove_tanggalChanged();
    partial void OnAprove_HCChanging(System.Nullable<bool> value);
    partial void OnAprove_HCChanged();
    partial void OnAprove_HC_byChanging(string value);
    partial void OnAprove_HC_byChanged();
    partial void OnAprove_HC_tanggalChanging(System.Nullable<System.DateTime> value);
    partial void OnAprove_HC_tanggalChanged();
    partial void OnTindakanChanging(string value);
    partial void OnTindakanChanged();
    partial void OnTgl_TindakanChanging(System.Nullable<System.DateTime> value);
    partial void OnTgl_TindakanChanged();
    #endregion
		
		public lembarkerja()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrp", DbType="NVarChar(10)")]
		public string nrp
		{
			get
			{
				return this._nrp;
			}
			set
			{
				if ((this._nrp != value))
				{
					this.OnnrpChanging(value);
					this.SendPropertyChanging();
					this._nrp = value;
					this.SendPropertyChanged("nrp");
					this.OnnrpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="DateTime")]
		public System.Nullable<System.DateTime> tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this.OntanggalChanging(value);
					this.SendPropertyChanging();
					this._tanggal = value;
					this.SendPropertyChanged("tanggal");
					this.OntanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shift", DbType="NVarChar(50)")]
		public string shift
		{
			get
			{
				return this._shift;
			}
			set
			{
				if ((this._shift != value))
				{
					this.OnshiftChanging(value);
					this.SendPropertyChanging();
					this._shift = value;
					this.SendPropertyChanged("shift");
					this.OnshiftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[cn unit]", Storage="_cn_unit", DbType="NVarChar(20)")]
		public string cn_unit
		{
			get
			{
				return this._cn_unit;
			}
			set
			{
				if ((this._cn_unit != value))
				{
					this.Oncn_unitChanging(value);
					this.SendPropertyChanging();
					this._cn_unit = value;
					this.SendPropertyChanged("cn_unit");
					this.Oncn_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alat", DbType="NVarChar(50)")]
		public string Alat
		{
			get
			{
				return this._Alat;
			}
			set
			{
				if ((this._Alat != value))
				{
					this.OnAlatChanging(value);
					this.SendPropertyChanging();
					this._Alat = value;
					this.SendPropertyChanged("Alat");
					this.OnAlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jk", DbType="Float")]
		public System.Nullable<double> jk
		{
			get
			{
				return this._jk;
			}
			set
			{
				if ((this._jk != value))
				{
					this.OnjkChanging(value);
					this.SendPropertyChanging();
					this._jk = value;
					this.SendPropertyChanged("jk");
					this.OnjkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jkp_opr", DbType="Float")]
		public System.Nullable<double> jkp_opr
		{
			get
			{
				return this._jkp_opr;
			}
			set
			{
				if ((this._jkp_opr != value))
				{
					this.Onjkp_oprChanging(value);
					this.SendPropertyChanging();
					this._jkp_opr = value;
					this.SendPropertyChanged("jkp_opr");
					this.Onjkp_oprChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rest_time", DbType="Float")]
		public System.Nullable<double> rest_time
		{
			get
			{
				return this._rest_time;
			}
			set
			{
				if ((this._rest_time != value))
				{
					this.Onrest_timeChanging(value);
					this.SendPropertyChanging();
					this._rest_time = value;
					this.SendPropertyChanged("rest_time");
					this.Onrest_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Absent", DbType="VarChar(50)")]
		public string Absent
		{
			get
			{
				return this._Absent;
			}
			set
			{
				if ((this._Absent != value))
				{
					this.OnAbsentChanging(value);
					this.SendPropertyChanging();
					this._Absent = value;
					this.SendPropertyChanged("Absent");
					this.OnAbsentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PemotongUlap", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PemotongUlap
		{
			get
			{
				return this._PemotongUlap;
			}
			set
			{
				if ((this._PemotongUlap != value))
				{
					this.OnPemotongUlapChanging(value);
					this.SendPropertyChanging();
					this._PemotongUlap = value;
					this.SendPropertyChanged("PemotongUlap");
					this.OnPemotongUlapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TingkatSP", DbType="NVarChar(3)")]
		public string TingkatSP
		{
			get
			{
				return this._TingkatSP;
			}
			set
			{
				if ((this._TingkatSP != value))
				{
					this.OnTingkatSPChanging(value);
					this.SendPropertyChanging();
					this._TingkatSP = value;
					this.SendPropertyChanged("TingkatSP");
					this.OnTingkatSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[in]", Storage="_in", DbType="DateTime")]
		public System.Nullable<System.DateTime> @in
		{
			get
			{
				return this._in;
			}
			set
			{
				if ((this._in != value))
				{
					this.OninChanging(value);
					this.SendPropertyChanging();
					this._in = value;
					this.SendPropertyChanged("@in");
					this.OninChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="out", Storage="_out", DbType="DateTime")]
		public System.Nullable<System.DateTime> @out
		{
			get
			{
				return this._out;
			}
			set
			{
				if ((this._out != value))
				{
					this.OnoutChanging(value);
					this.SendPropertyChanging();
					this._out = value;
					this.SendPropertyChanged("@out");
					this.OnoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jk1", DbType="Float")]
		public System.Nullable<double> jk1
		{
			get
			{
				return this._jk1;
			}
			set
			{
				if ((this._jk1 != value))
				{
					this.Onjk1Changing(value);
					this.SendPropertyChanging();
					this._jk1 = value;
					this.SendPropertyChanged("jk1");
					this.Onjk1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RosterCode", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> RosterCode
		{
			get
			{
				return this._RosterCode;
			}
			set
			{
				if ((this._RosterCode != value))
				{
					this.OnRosterCodeChanging(value);
					this.SendPropertyChanging();
					this._RosterCode = value;
					this.SendPropertyChanged("RosterCode");
					this.OnRosterCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoMesin1", DbType="NVarChar(2)")]
		public string NoMesin1
		{
			get
			{
				return this._NoMesin1;
			}
			set
			{
				if ((this._NoMesin1 != value))
				{
					this.OnNoMesin1Changing(value);
					this.SendPropertyChanging();
					this._NoMesin1 = value;
					this.SendPropertyChanged("NoMesin1");
					this.OnNoMesin1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoMesin2", DbType="NVarChar(2)")]
		public string NoMesin2
		{
			get
			{
				return this._NoMesin2;
			}
			set
			{
				if ((this._NoMesin2 != value))
				{
					this.OnNoMesin2Changing(value);
					this.SendPropertyChanging();
					this._NoMesin2 = value;
					this.SendPropertyChanged("NoMesin2");
					this.OnNoMesin2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terlambat", DbType="DateTime")]
		public System.Nullable<System.DateTime> Terlambat
		{
			get
			{
				return this._Terlambat;
			}
			set
			{
				if ((this._Terlambat != value))
				{
					this.OnTerlambatChanging(value);
					this.SendPropertyChanging();
					this._Terlambat = value;
					this.SendPropertyChanged("Terlambat");
					this.OnTerlambatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKL", DbType="Float")]
		public System.Nullable<double> SKL
		{
			get
			{
				return this._SKL;
			}
			set
			{
				if ((this._SKL != value))
				{
					this.OnSKLChanging(value);
					this.SendPropertyChanging();
					this._SKL = value;
					this.SendPropertyChanged("SKL");
					this.OnSKLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKL2", DbType="Float")]
		public System.Nullable<double> SKL2
		{
			get
			{
				return this._SKL2;
			}
			set
			{
				if ((this._SKL2 != value))
				{
					this.OnSKL2Changing(value);
					this.SendPropertyChanging();
					this._SKL2 = value;
					this.SendPropertyChanged("SKL2");
					this.OnSKL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKL3", DbType="Float")]
		public System.Nullable<double> SKL3
		{
			get
			{
				return this._SKL3;
			}
			set
			{
				if ((this._SKL3 != value))
				{
					this.OnSKL3Changing(value);
					this.SendPropertyChanging();
					this._SKL3 = value;
					this.SendPropertyChanged("SKL3");
					this.OnSKL3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKL1", DbType="Float")]
		public System.Nullable<double> SKL1
		{
			get
			{
				return this._SKL1;
			}
			set
			{
				if ((this._SKL1 != value))
				{
					this.OnSKL1Changing(value);
					this.SendPropertyChanging();
					this._SKL1 = value;
					this.SendPropertyChanged("SKL1");
					this.OnSKL1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InputBY", DbType="VarChar(10)")]
		public string InputBY
		{
			get
			{
				return this._InputBY;
			}
			set
			{
				if ((this._InputBY != value))
				{
					this.OnInputBYChanging(value);
					this.SendPropertyChanging();
					this._InputBY = value;
					this.SendPropertyChanged("InputBY");
					this.OnInputBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGLINPUT", DbType="DateTime")]
		public System.Nullable<System.DateTime> TGLINPUT
		{
			get
			{
				return this._TGLINPUT;
			}
			set
			{
				if ((this._TGLINPUT != value))
				{
					this.OnTGLINPUTChanging(value);
					this.SendPropertyChanging();
					this._TGLINPUT = value;
					this.SendPropertyChanged("TGLINPUT");
					this.OnTGLINPUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpoUpdateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> IpoUpdateTime
		{
			get
			{
				return this._IpoUpdateTime;
			}
			set
			{
				if ((this._IpoUpdateTime != value))
				{
					this.OnIpoUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._IpoUpdateTime = value;
					this.SendPropertyChanged("IpoUpdateTime");
					this.OnIpoUpdateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alat_follow_up", DbType="NVarChar(50)")]
		public string alat_follow_up
		{
			get
			{
				return this._alat_follow_up;
			}
			set
			{
				if ((this._alat_follow_up != value))
				{
					this.Onalat_follow_upChanging(value);
					this.SendPropertyChanging();
					this._alat_follow_up = value;
					this.SendPropertyChanged("alat_follow_up");
					this.Onalat_follow_upChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Follow_Up", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Follow_Up
		{
			get
			{
				return this._Follow_Up;
			}
			set
			{
				if ((this._Follow_Up != value))
				{
					this.OnFollow_UpChanging(value);
					this.SendPropertyChanging();
					this._Follow_Up = value;
					this.SendPropertyChanged("Follow_Up");
					this.OnFollow_UpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Progress", DbType="VarChar(50)")]
		public string Progress
		{
			get
			{
				return this._Progress;
			}
			set
			{
				if ((this._Progress != value))
				{
					this.OnProgressChanging(value);
					this.SendPropertyChanging();
					this._Progress = value;
					this.SendPropertyChanged("Progress");
					this.OnProgressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Problem", DbType="Bit")]
		public System.Nullable<bool> Problem
		{
			get
			{
				return this._Problem;
			}
			set
			{
				if ((this._Problem != value))
				{
					this.OnProblemChanging(value);
					this.SendPropertyChanging();
					this._Problem = value;
					this.SendPropertyChanged("Problem");
					this.OnProblemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alat_approve_status", DbType="NVarChar(50)")]
		public string alat_approve_status
		{
			get
			{
				return this._alat_approve_status;
			}
			set
			{
				if ((this._alat_approve_status != value))
				{
					this.Onalat_approve_statusChanging(value);
					this.SendPropertyChanging();
					this._alat_approve_status = value;
					this.SendPropertyChanged("alat_approve_status");
					this.Onalat_approve_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ket_Lembur", DbType="VarChar(50)")]
		public string Ket_Lembur
		{
			get
			{
				return this._Ket_Lembur;
			}
			set
			{
				if ((this._Ket_Lembur != value))
				{
					this.OnKet_LemburChanging(value);
					this.SendPropertyChanging();
					this._Ket_Lembur = value;
					this.SendPropertyChanged("Ket_Lembur");
					this.OnKet_LemburChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_Atasan", DbType="Bit")]
		public System.Nullable<bool> Aprove_Atasan
		{
			get
			{
				return this._Aprove_Atasan;
			}
			set
			{
				if ((this._Aprove_Atasan != value))
				{
					this.OnAprove_AtasanChanging(value);
					this.SendPropertyChanging();
					this._Aprove_Atasan = value;
					this.SendPropertyChanged("Aprove_Atasan");
					this.OnAprove_AtasanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_by", DbType="VarChar(50)")]
		public string Aprove_by
		{
			get
			{
				return this._Aprove_by;
			}
			set
			{
				if ((this._Aprove_by != value))
				{
					this.OnAprove_byChanging(value);
					this.SendPropertyChanging();
					this._Aprove_by = value;
					this.SendPropertyChanged("Aprove_by");
					this.OnAprove_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_tanggal", DbType="DateTime")]
		public System.Nullable<System.DateTime> Aprove_tanggal
		{
			get
			{
				return this._Aprove_tanggal;
			}
			set
			{
				if ((this._Aprove_tanggal != value))
				{
					this.OnAprove_tanggalChanging(value);
					this.SendPropertyChanging();
					this._Aprove_tanggal = value;
					this.SendPropertyChanged("Aprove_tanggal");
					this.OnAprove_tanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_HC", DbType="Bit")]
		public System.Nullable<bool> Aprove_HC
		{
			get
			{
				return this._Aprove_HC;
			}
			set
			{
				if ((this._Aprove_HC != value))
				{
					this.OnAprove_HCChanging(value);
					this.SendPropertyChanging();
					this._Aprove_HC = value;
					this.SendPropertyChanged("Aprove_HC");
					this.OnAprove_HCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_HC_by", DbType="VarChar(50)")]
		public string Aprove_HC_by
		{
			get
			{
				return this._Aprove_HC_by;
			}
			set
			{
				if ((this._Aprove_HC_by != value))
				{
					this.OnAprove_HC_byChanging(value);
					this.SendPropertyChanging();
					this._Aprove_HC_by = value;
					this.SendPropertyChanged("Aprove_HC_by");
					this.OnAprove_HC_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_HC_tanggal", DbType="DateTime")]
		public System.Nullable<System.DateTime> Aprove_HC_tanggal
		{
			get
			{
				return this._Aprove_HC_tanggal;
			}
			set
			{
				if ((this._Aprove_HC_tanggal != value))
				{
					this.OnAprove_HC_tanggalChanging(value);
					this.SendPropertyChanging();
					this._Aprove_HC_tanggal = value;
					this.SendPropertyChanged("Aprove_HC_tanggal");
					this.OnAprove_HC_tanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tindakan", DbType="VarChar(50)")]
		public string Tindakan
		{
			get
			{
				return this._Tindakan;
			}
			set
			{
				if ((this._Tindakan != value))
				{
					this.OnTindakanChanging(value);
					this.SendPropertyChanging();
					this._Tindakan = value;
					this.SendPropertyChanged("Tindakan");
					this.OnTindakanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tgl_Tindakan", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tgl_Tindakan
		{
			get
			{
				return this._Tgl_Tindakan;
			}
			set
			{
				if ((this._Tgl_Tindakan != value))
				{
					this.OnTgl_TindakanChanging(value);
					this.SendPropertyChanging();
					this._Tgl_Tindakan = value;
					this.SendPropertyChanged("Tgl_Tindakan");
					this.OnTgl_TindakanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lembarkerja_temp_new")]
	public partial class lembarkerja_temp_new
	{
		
		private string _SESSION_UPLOAD;
		
		private string _CREATED_BY;
		
		private System.Nullable<System.DateTime> _CREATED_DATE;
		
		private string _nrp;
		
		private string _tanggal;
		
		private string _shift;
		
		private string _cn_unit;
		
		private string _Alat;
		
		private string _jk;
		
		private string _jkp_opr;
		
		private string _rest_time;
		
		private string _Absent;
		
		private string _PemotongUlap;
		
		private string _TingkatSP;
		
		private string _in;
		
		private string _out;
		
		private string _jk1;
		
		private string _RosterCode;
		
		private string _NoMesin1;
		
		private string _NoMesin2;
		
		private string _Terlambat;
		
		private string _SKL;
		
		private string _SKL2;
		
		private string _SKL3;
		
		private string _SKL1;
		
		private string _InputBY;
		
		private string _TGLINPUT;
		
		private string _IpoUpdateTime;
		
		private string _Follow_Up;
		
		private string _Progress;
		
		private string _Problem;
		
		private string _Ket_Lembur;
		
		private string _Aprove_Atasan;
		
		private string _Aprove_by;
		
		private string _Aprove_tanggal;
		
		private string _Aprove_HC;
		
		private string _Aprove_HC_by;
		
		private string _Aprove_HC_tanggal;
		
		private string _Tindakan;
		
		private string _Tgl_Tindakan;
		
		public lembarkerja_temp_new()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSION_UPLOAD", DbType="VarChar(50)")]
		public string SESSION_UPLOAD
		{
			get
			{
				return this._SESSION_UPLOAD;
			}
			set
			{
				if ((this._SESSION_UPLOAD != value))
				{
					this._SESSION_UPLOAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY", DbType="VarChar(50)")]
		public string CREATED_BY
		{
			get
			{
				return this._CREATED_BY;
			}
			set
			{
				if ((this._CREATED_BY != value))
				{
					this._CREATED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_DATE
		{
			get
			{
				return this._CREATED_DATE;
			}
			set
			{
				if ((this._CREATED_DATE != value))
				{
					this._CREATED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrp", DbType="VarChar(50)")]
		public string nrp
		{
			get
			{
				return this._nrp;
			}
			set
			{
				if ((this._nrp != value))
				{
					this._nrp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="VarChar(50)")]
		public string tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this._tanggal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shift", DbType="VarChar(50)")]
		public string shift
		{
			get
			{
				return this._shift;
			}
			set
			{
				if ((this._shift != value))
				{
					this._shift = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[cn unit]", Storage="_cn_unit", DbType="VarChar(50)")]
		public string cn_unit
		{
			get
			{
				return this._cn_unit;
			}
			set
			{
				if ((this._cn_unit != value))
				{
					this._cn_unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alat", DbType="VarChar(50)")]
		public string Alat
		{
			get
			{
				return this._Alat;
			}
			set
			{
				if ((this._Alat != value))
				{
					this._Alat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jk", DbType="VarChar(50)")]
		public string jk
		{
			get
			{
				return this._jk;
			}
			set
			{
				if ((this._jk != value))
				{
					this._jk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jkp_opr", DbType="VarChar(50)")]
		public string jkp_opr
		{
			get
			{
				return this._jkp_opr;
			}
			set
			{
				if ((this._jkp_opr != value))
				{
					this._jkp_opr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rest_time", DbType="VarChar(50)")]
		public string rest_time
		{
			get
			{
				return this._rest_time;
			}
			set
			{
				if ((this._rest_time != value))
				{
					this._rest_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Absent", DbType="VarChar(50)")]
		public string Absent
		{
			get
			{
				return this._Absent;
			}
			set
			{
				if ((this._Absent != value))
				{
					this._Absent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PemotongUlap", DbType="VarChar(50)")]
		public string PemotongUlap
		{
			get
			{
				return this._PemotongUlap;
			}
			set
			{
				if ((this._PemotongUlap != value))
				{
					this._PemotongUlap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TingkatSP", DbType="VarChar(50)")]
		public string TingkatSP
		{
			get
			{
				return this._TingkatSP;
			}
			set
			{
				if ((this._TingkatSP != value))
				{
					this._TingkatSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[in]", Storage="_in", DbType="VarChar(50)")]
		public string @in
		{
			get
			{
				return this._in;
			}
			set
			{
				if ((this._in != value))
				{
					this._in = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="out", Storage="_out", DbType="VarChar(50)")]
		public string @out
		{
			get
			{
				return this._out;
			}
			set
			{
				if ((this._out != value))
				{
					this._out = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jk1", DbType="VarChar(50)")]
		public string jk1
		{
			get
			{
				return this._jk1;
			}
			set
			{
				if ((this._jk1 != value))
				{
					this._jk1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RosterCode", DbType="VarChar(50)")]
		public string RosterCode
		{
			get
			{
				return this._RosterCode;
			}
			set
			{
				if ((this._RosterCode != value))
				{
					this._RosterCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoMesin1", DbType="VarChar(50)")]
		public string NoMesin1
		{
			get
			{
				return this._NoMesin1;
			}
			set
			{
				if ((this._NoMesin1 != value))
				{
					this._NoMesin1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoMesin2", DbType="VarChar(50)")]
		public string NoMesin2
		{
			get
			{
				return this._NoMesin2;
			}
			set
			{
				if ((this._NoMesin2 != value))
				{
					this._NoMesin2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terlambat", DbType="VarChar(50)")]
		public string Terlambat
		{
			get
			{
				return this._Terlambat;
			}
			set
			{
				if ((this._Terlambat != value))
				{
					this._Terlambat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKL", DbType="VarChar(50)")]
		public string SKL
		{
			get
			{
				return this._SKL;
			}
			set
			{
				if ((this._SKL != value))
				{
					this._SKL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKL2", DbType="VarChar(50)")]
		public string SKL2
		{
			get
			{
				return this._SKL2;
			}
			set
			{
				if ((this._SKL2 != value))
				{
					this._SKL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKL3", DbType="VarChar(50)")]
		public string SKL3
		{
			get
			{
				return this._SKL3;
			}
			set
			{
				if ((this._SKL3 != value))
				{
					this._SKL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKL1", DbType="VarChar(50)")]
		public string SKL1
		{
			get
			{
				return this._SKL1;
			}
			set
			{
				if ((this._SKL1 != value))
				{
					this._SKL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InputBY", DbType="VarChar(50)")]
		public string InputBY
		{
			get
			{
				return this._InputBY;
			}
			set
			{
				if ((this._InputBY != value))
				{
					this._InputBY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGLINPUT", DbType="VarChar(50)")]
		public string TGLINPUT
		{
			get
			{
				return this._TGLINPUT;
			}
			set
			{
				if ((this._TGLINPUT != value))
				{
					this._TGLINPUT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpoUpdateTime", DbType="VarChar(50)")]
		public string IpoUpdateTime
		{
			get
			{
				return this._IpoUpdateTime;
			}
			set
			{
				if ((this._IpoUpdateTime != value))
				{
					this._IpoUpdateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Follow_Up", DbType="VarChar(500)")]
		public string Follow_Up
		{
			get
			{
				return this._Follow_Up;
			}
			set
			{
				if ((this._Follow_Up != value))
				{
					this._Follow_Up = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Progress", DbType="VarChar(50)")]
		public string Progress
		{
			get
			{
				return this._Progress;
			}
			set
			{
				if ((this._Progress != value))
				{
					this._Progress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Problem", DbType="VarChar(50)")]
		public string Problem
		{
			get
			{
				return this._Problem;
			}
			set
			{
				if ((this._Problem != value))
				{
					this._Problem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ket_Lembur", DbType="VarChar(50)")]
		public string Ket_Lembur
		{
			get
			{
				return this._Ket_Lembur;
			}
			set
			{
				if ((this._Ket_Lembur != value))
				{
					this._Ket_Lembur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_Atasan", DbType="VarChar(50)")]
		public string Aprove_Atasan
		{
			get
			{
				return this._Aprove_Atasan;
			}
			set
			{
				if ((this._Aprove_Atasan != value))
				{
					this._Aprove_Atasan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_by", DbType="VarChar(50)")]
		public string Aprove_by
		{
			get
			{
				return this._Aprove_by;
			}
			set
			{
				if ((this._Aprove_by != value))
				{
					this._Aprove_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_tanggal", DbType="VarChar(50)")]
		public string Aprove_tanggal
		{
			get
			{
				return this._Aprove_tanggal;
			}
			set
			{
				if ((this._Aprove_tanggal != value))
				{
					this._Aprove_tanggal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_HC", DbType="VarChar(50)")]
		public string Aprove_HC
		{
			get
			{
				return this._Aprove_HC;
			}
			set
			{
				if ((this._Aprove_HC != value))
				{
					this._Aprove_HC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_HC_by", DbType="VarChar(50)")]
		public string Aprove_HC_by
		{
			get
			{
				return this._Aprove_HC_by;
			}
			set
			{
				if ((this._Aprove_HC_by != value))
				{
					this._Aprove_HC_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_HC_tanggal", DbType="VarChar(50)")]
		public string Aprove_HC_tanggal
		{
			get
			{
				return this._Aprove_HC_tanggal;
			}
			set
			{
				if ((this._Aprove_HC_tanggal != value))
				{
					this._Aprove_HC_tanggal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tindakan", DbType="VarChar(500)")]
		public string Tindakan
		{
			get
			{
				return this._Tindakan;
			}
			set
			{
				if ((this._Tindakan != value))
				{
					this._Tindakan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tgl_Tindakan", DbType="VarChar(50)")]
		public string Tgl_Tindakan
		{
			get
			{
				return this._Tgl_Tindakan;
			}
			set
			{
				if ((this._Tgl_Tindakan != value))
				{
					this._Tgl_Tindakan = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AbsentCode")]
	public partial class AbsentCode
	{
		
		private string _Code;
		
		private string _Keterangan;
		
		public AbsentCode()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keterangan", DbType="VarChar(50)")]
		public string Keterangan
		{
			get
			{
				return this._Keterangan;
			}
			set
			{
				if ((this._Keterangan != value))
				{
					this._Keterangan = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_M_INJEK_DEPT_ALL")]
	public partial class VW_M_INJEK_DEPT_ALL
	{
		
		private string _nrp;
		
		private System.Nullable<System.DateTime> _tanggal;
		
		private string _shift;
		
		private string _Absent;
		
		private System.Nullable<System.DateTime> _in;
		
		private System.Nullable<System.DateTime> _out;
		
		private string _Keterangan;
		
		private string _revisiby;
		
		private System.Nullable<System.DateTime> _tglrevisi;
		
		public VW_M_INJEK_DEPT_ALL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrp", DbType="NVarChar(10)")]
		public string nrp
		{
			get
			{
				return this._nrp;
			}
			set
			{
				if ((this._nrp != value))
				{
					this._nrp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="DateTime")]
		public System.Nullable<System.DateTime> tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this._tanggal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shift", DbType="NVarChar(50)")]
		public string shift
		{
			get
			{
				return this._shift;
			}
			set
			{
				if ((this._shift != value))
				{
					this._shift = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Absent", DbType="VarChar(50)")]
		public string Absent
		{
			get
			{
				return this._Absent;
			}
			set
			{
				if ((this._Absent != value))
				{
					this._Absent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[in]", Storage="_in", DbType="DateTime")]
		public System.Nullable<System.DateTime> @in
		{
			get
			{
				return this._in;
			}
			set
			{
				if ((this._in != value))
				{
					this._in = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="out", Storage="_out", DbType="DateTime")]
		public System.Nullable<System.DateTime> @out
		{
			get
			{
				return this._out;
			}
			set
			{
				if ((this._out != value))
				{
					this._out = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keterangan", DbType="VarChar(255)")]
		public string Keterangan
		{
			get
			{
				return this._Keterangan;
			}
			set
			{
				if ((this._Keterangan != value))
				{
					this._Keterangan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_revisiby", DbType="VarChar(10)")]
		public string revisiby
		{
			get
			{
				return this._revisiby;
			}
			set
			{
				if ((this._revisiby != value))
				{
					this._revisiby = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tglrevisi", DbType="DateTime")]
		public System.Nullable<System.DateTime> tglrevisi
		{
			get
			{
				return this._tglrevisi;
			}
			set
			{
				if ((this._tglrevisi != value))
				{
					this._tglrevisi = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblinjekdept1")]
	public partial class tblinjekdept1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private string _nrp;
		
		private System.Nullable<System.DateTime> _tanggal;
		
		private string _shift;
		
		private System.Nullable<System.DateTime> _in;
		
		private System.Nullable<System.DateTime> _out;
		
		private string _Keterangan;
		
		private string _revisiby;
		
		private System.Nullable<System.DateTime> _tglrevisi;
		
		private System.Nullable<bool> _aprovehead;
		
		private System.Nullable<System.DateTime> _tglhead;
		
		private string _nrphead;
		
		private string _cathead;
		
		private string _status;
		
		private System.Nullable<bool> _aprovehr;
		
		private string _nrphr;
		
		private string _cathr;
		
		private System.Nullable<System.DateTime> _tglhr;
		
		private string _Alat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnnrpChanging(string value);
    partial void OnnrpChanged();
    partial void OntanggalChanging(System.Nullable<System.DateTime> value);
    partial void OntanggalChanged();
    partial void OnshiftChanging(string value);
    partial void OnshiftChanged();
    partial void OninChanging(System.Nullable<System.DateTime> value);
    partial void OninChanged();
    partial void OnoutChanging(System.Nullable<System.DateTime> value);
    partial void OnoutChanged();
    partial void OnKeteranganChanging(string value);
    partial void OnKeteranganChanged();
    partial void OnrevisibyChanging(string value);
    partial void OnrevisibyChanged();
    partial void OntglrevisiChanging(System.Nullable<System.DateTime> value);
    partial void OntglrevisiChanged();
    partial void OnaproveheadChanging(System.Nullable<bool> value);
    partial void OnaproveheadChanged();
    partial void OntglheadChanging(System.Nullable<System.DateTime> value);
    partial void OntglheadChanged();
    partial void OnnrpheadChanging(string value);
    partial void OnnrpheadChanged();
    partial void OncatheadChanging(string value);
    partial void OncatheadChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnaprovehrChanging(System.Nullable<bool> value);
    partial void OnaprovehrChanged();
    partial void OnnrphrChanging(string value);
    partial void OnnrphrChanged();
    partial void OncathrChanging(string value);
    partial void OncathrChanged();
    partial void OntglhrChanging(System.Nullable<System.DateTime> value);
    partial void OntglhrChanged();
    partial void OnAlatChanging(string value);
    partial void OnAlatChanged();
    #endregion
		
		public tblinjekdept1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrp", DbType="VarChar(10)")]
		public string nrp
		{
			get
			{
				return this._nrp;
			}
			set
			{
				if ((this._nrp != value))
				{
					this.OnnrpChanging(value);
					this.SendPropertyChanging();
					this._nrp = value;
					this.SendPropertyChanged("nrp");
					this.OnnrpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="DateTime")]
		public System.Nullable<System.DateTime> tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this.OntanggalChanging(value);
					this.SendPropertyChanging();
					this._tanggal = value;
					this.SendPropertyChanged("tanggal");
					this.OntanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shift", DbType="VarChar(2)")]
		public string shift
		{
			get
			{
				return this._shift;
			}
			set
			{
				if ((this._shift != value))
				{
					this.OnshiftChanging(value);
					this.SendPropertyChanging();
					this._shift = value;
					this.SendPropertyChanged("shift");
					this.OnshiftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[in]", Storage="_in", DbType="DateTime")]
		public System.Nullable<System.DateTime> @in
		{
			get
			{
				return this._in;
			}
			set
			{
				if ((this._in != value))
				{
					this.OninChanging(value);
					this.SendPropertyChanging();
					this._in = value;
					this.SendPropertyChanged("@in");
					this.OninChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="out", Storage="_out", DbType="DateTime")]
		public System.Nullable<System.DateTime> @out
		{
			get
			{
				return this._out;
			}
			set
			{
				if ((this._out != value))
				{
					this.OnoutChanging(value);
					this.SendPropertyChanging();
					this._out = value;
					this.SendPropertyChanged("@out");
					this.OnoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keterangan", DbType="VarChar(255)")]
		public string Keterangan
		{
			get
			{
				return this._Keterangan;
			}
			set
			{
				if ((this._Keterangan != value))
				{
					this.OnKeteranganChanging(value);
					this.SendPropertyChanging();
					this._Keterangan = value;
					this.SendPropertyChanged("Keterangan");
					this.OnKeteranganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_revisiby", DbType="VarChar(10)")]
		public string revisiby
		{
			get
			{
				return this._revisiby;
			}
			set
			{
				if ((this._revisiby != value))
				{
					this.OnrevisibyChanging(value);
					this.SendPropertyChanging();
					this._revisiby = value;
					this.SendPropertyChanged("revisiby");
					this.OnrevisibyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tglrevisi", DbType="DateTime")]
		public System.Nullable<System.DateTime> tglrevisi
		{
			get
			{
				return this._tglrevisi;
			}
			set
			{
				if ((this._tglrevisi != value))
				{
					this.OntglrevisiChanging(value);
					this.SendPropertyChanging();
					this._tglrevisi = value;
					this.SendPropertyChanged("tglrevisi");
					this.OntglrevisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aprovehead", DbType="Bit")]
		public System.Nullable<bool> aprovehead
		{
			get
			{
				return this._aprovehead;
			}
			set
			{
				if ((this._aprovehead != value))
				{
					this.OnaproveheadChanging(value);
					this.SendPropertyChanging();
					this._aprovehead = value;
					this.SendPropertyChanged("aprovehead");
					this.OnaproveheadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tglhead", DbType="DateTime")]
		public System.Nullable<System.DateTime> tglhead
		{
			get
			{
				return this._tglhead;
			}
			set
			{
				if ((this._tglhead != value))
				{
					this.OntglheadChanging(value);
					this.SendPropertyChanging();
					this._tglhead = value;
					this.SendPropertyChanged("tglhead");
					this.OntglheadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrphead", DbType="VarChar(10)")]
		public string nrphead
		{
			get
			{
				return this._nrphead;
			}
			set
			{
				if ((this._nrphead != value))
				{
					this.OnnrpheadChanging(value);
					this.SendPropertyChanging();
					this._nrphead = value;
					this.SendPropertyChanged("nrphead");
					this.OnnrpheadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cathead", DbType="VarChar(50)")]
		public string cathead
		{
			get
			{
				return this._cathead;
			}
			set
			{
				if ((this._cathead != value))
				{
					this.OncatheadChanging(value);
					this.SendPropertyChanging();
					this._cathead = value;
					this.SendPropertyChanged("cathead");
					this.OncatheadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(1)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aprovehr", DbType="Bit")]
		public System.Nullable<bool> aprovehr
		{
			get
			{
				return this._aprovehr;
			}
			set
			{
				if ((this._aprovehr != value))
				{
					this.OnaprovehrChanging(value);
					this.SendPropertyChanging();
					this._aprovehr = value;
					this.SendPropertyChanged("aprovehr");
					this.OnaprovehrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrphr", DbType="VarChar(10)")]
		public string nrphr
		{
			get
			{
				return this._nrphr;
			}
			set
			{
				if ((this._nrphr != value))
				{
					this.OnnrphrChanging(value);
					this.SendPropertyChanging();
					this._nrphr = value;
					this.SendPropertyChanged("nrphr");
					this.OnnrphrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cathr", DbType="VarChar(50)")]
		public string cathr
		{
			get
			{
				return this._cathr;
			}
			set
			{
				if ((this._cathr != value))
				{
					this.OncathrChanging(value);
					this.SendPropertyChanging();
					this._cathr = value;
					this.SendPropertyChanged("cathr");
					this.OncathrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tglhr", DbType="DateTime")]
		public System.Nullable<System.DateTime> tglhr
		{
			get
			{
				return this._tglhr;
			}
			set
			{
				if ((this._tglhr != value))
				{
					this.OntglhrChanging(value);
					this.SendPropertyChanging();
					this._tglhr = value;
					this.SendPropertyChanged("tglhr");
					this.OntglhrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alat", DbType="VarChar(50)")]
		public string Alat
		{
			get
			{
				return this._Alat;
			}
			set
			{
				if ((this._Alat != value))
				{
					this.OnAlatChanging(value);
					this.SendPropertyChanging();
					this._Alat = value;
					this.SendPropertyChanged("Alat");
					this.OnAlatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lembarkerja_BACKUP")]
	public partial class lembarkerja_BACKUP
	{
		
		private decimal _id;
		
		private string _nrp;
		
		private System.Nullable<System.DateTime> _tanggal;
		
		private string _shift;
		
		private string _cn_unit;
		
		private string _Alat;
		
		private System.Nullable<double> _jk;
		
		private System.Nullable<double> _jkp_opr;
		
		private System.Nullable<double> _rest_time;
		
		private string _Absent;
		
		private System.Nullable<decimal> _PemotongUlap;
		
		private string _TingkatSP;
		
		private System.Nullable<System.DateTime> _in;
		
		private System.Nullable<System.DateTime> _out;
		
		private System.Nullable<double> _jk1;
		
		private System.Nullable<decimal> _RosterCode;
		
		private string _NoMesin1;
		
		private string _NoMesin2;
		
		private System.Nullable<System.DateTime> _Terlambat;
		
		private System.Nullable<double> _SKL;
		
		private System.Nullable<double> _SKL2;
		
		private System.Nullable<double> _SKL3;
		
		private System.Nullable<double> _SKL1;
		
		private string _InputBY;
		
		private System.Nullable<System.DateTime> _TGLINPUT;
		
		private System.Nullable<System.DateTime> _IpoUpdateTime;
		
		private string _alat_follow_up;
		
		private string _Follow_Up;
		
		private string _Progress;
		
		private System.Nullable<bool> _Problem;
		
		private string _alat_approve_status;
		
		private string _Ket_Lembur;
		
		private System.Nullable<bool> _Aprove_Atasan;
		
		private string _Aprove_by;
		
		private System.Nullable<System.DateTime> _Aprove_tanggal;
		
		private System.Nullable<bool> _Aprove_HC;
		
		private string _Aprove_HC_by;
		
		private System.Nullable<System.DateTime> _Aprove_HC_tanggal;
		
		public lembarkerja_BACKUP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Decimal(18,0) NOT NULL")]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrp", DbType="NVarChar(10)")]
		public string nrp
		{
			get
			{
				return this._nrp;
			}
			set
			{
				if ((this._nrp != value))
				{
					this._nrp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="DateTime")]
		public System.Nullable<System.DateTime> tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this._tanggal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shift", DbType="NVarChar(50)")]
		public string shift
		{
			get
			{
				return this._shift;
			}
			set
			{
				if ((this._shift != value))
				{
					this._shift = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[cn unit]", Storage="_cn_unit", DbType="NVarChar(20)")]
		public string cn_unit
		{
			get
			{
				return this._cn_unit;
			}
			set
			{
				if ((this._cn_unit != value))
				{
					this._cn_unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alat", DbType="NVarChar(50)")]
		public string Alat
		{
			get
			{
				return this._Alat;
			}
			set
			{
				if ((this._Alat != value))
				{
					this._Alat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jk", DbType="Float")]
		public System.Nullable<double> jk
		{
			get
			{
				return this._jk;
			}
			set
			{
				if ((this._jk != value))
				{
					this._jk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jkp_opr", DbType="Float")]
		public System.Nullable<double> jkp_opr
		{
			get
			{
				return this._jkp_opr;
			}
			set
			{
				if ((this._jkp_opr != value))
				{
					this._jkp_opr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rest_time", DbType="Float")]
		public System.Nullable<double> rest_time
		{
			get
			{
				return this._rest_time;
			}
			set
			{
				if ((this._rest_time != value))
				{
					this._rest_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Absent", DbType="VarChar(50)")]
		public string Absent
		{
			get
			{
				return this._Absent;
			}
			set
			{
				if ((this._Absent != value))
				{
					this._Absent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PemotongUlap", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PemotongUlap
		{
			get
			{
				return this._PemotongUlap;
			}
			set
			{
				if ((this._PemotongUlap != value))
				{
					this._PemotongUlap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TingkatSP", DbType="NVarChar(3)")]
		public string TingkatSP
		{
			get
			{
				return this._TingkatSP;
			}
			set
			{
				if ((this._TingkatSP != value))
				{
					this._TingkatSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[in]", Storage="_in", DbType="DateTime")]
		public System.Nullable<System.DateTime> @in
		{
			get
			{
				return this._in;
			}
			set
			{
				if ((this._in != value))
				{
					this._in = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="out", Storage="_out", DbType="DateTime")]
		public System.Nullable<System.DateTime> @out
		{
			get
			{
				return this._out;
			}
			set
			{
				if ((this._out != value))
				{
					this._out = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jk1", DbType="Float")]
		public System.Nullable<double> jk1
		{
			get
			{
				return this._jk1;
			}
			set
			{
				if ((this._jk1 != value))
				{
					this._jk1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RosterCode", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> RosterCode
		{
			get
			{
				return this._RosterCode;
			}
			set
			{
				if ((this._RosterCode != value))
				{
					this._RosterCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoMesin1", DbType="NVarChar(2)")]
		public string NoMesin1
		{
			get
			{
				return this._NoMesin1;
			}
			set
			{
				if ((this._NoMesin1 != value))
				{
					this._NoMesin1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoMesin2", DbType="NVarChar(2)")]
		public string NoMesin2
		{
			get
			{
				return this._NoMesin2;
			}
			set
			{
				if ((this._NoMesin2 != value))
				{
					this._NoMesin2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terlambat", DbType="DateTime")]
		public System.Nullable<System.DateTime> Terlambat
		{
			get
			{
				return this._Terlambat;
			}
			set
			{
				if ((this._Terlambat != value))
				{
					this._Terlambat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKL", DbType="Float")]
		public System.Nullable<double> SKL
		{
			get
			{
				return this._SKL;
			}
			set
			{
				if ((this._SKL != value))
				{
					this._SKL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKL2", DbType="Float")]
		public System.Nullable<double> SKL2
		{
			get
			{
				return this._SKL2;
			}
			set
			{
				if ((this._SKL2 != value))
				{
					this._SKL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKL3", DbType="Float")]
		public System.Nullable<double> SKL3
		{
			get
			{
				return this._SKL3;
			}
			set
			{
				if ((this._SKL3 != value))
				{
					this._SKL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKL1", DbType="Float")]
		public System.Nullable<double> SKL1
		{
			get
			{
				return this._SKL1;
			}
			set
			{
				if ((this._SKL1 != value))
				{
					this._SKL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InputBY", DbType="VarChar(10)")]
		public string InputBY
		{
			get
			{
				return this._InputBY;
			}
			set
			{
				if ((this._InputBY != value))
				{
					this._InputBY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGLINPUT", DbType="DateTime")]
		public System.Nullable<System.DateTime> TGLINPUT
		{
			get
			{
				return this._TGLINPUT;
			}
			set
			{
				if ((this._TGLINPUT != value))
				{
					this._TGLINPUT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpoUpdateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> IpoUpdateTime
		{
			get
			{
				return this._IpoUpdateTime;
			}
			set
			{
				if ((this._IpoUpdateTime != value))
				{
					this._IpoUpdateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alat_follow_up", DbType="NVarChar(50)")]
		public string alat_follow_up
		{
			get
			{
				return this._alat_follow_up;
			}
			set
			{
				if ((this._alat_follow_up != value))
				{
					this._alat_follow_up = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Follow_Up", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Follow_Up
		{
			get
			{
				return this._Follow_Up;
			}
			set
			{
				if ((this._Follow_Up != value))
				{
					this._Follow_Up = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Progress", DbType="VarChar(50)")]
		public string Progress
		{
			get
			{
				return this._Progress;
			}
			set
			{
				if ((this._Progress != value))
				{
					this._Progress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Problem", DbType="Bit")]
		public System.Nullable<bool> Problem
		{
			get
			{
				return this._Problem;
			}
			set
			{
				if ((this._Problem != value))
				{
					this._Problem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alat_approve_status", DbType="NVarChar(50)")]
		public string alat_approve_status
		{
			get
			{
				return this._alat_approve_status;
			}
			set
			{
				if ((this._alat_approve_status != value))
				{
					this._alat_approve_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ket_Lembur", DbType="VarChar(50)")]
		public string Ket_Lembur
		{
			get
			{
				return this._Ket_Lembur;
			}
			set
			{
				if ((this._Ket_Lembur != value))
				{
					this._Ket_Lembur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_Atasan", DbType="Bit")]
		public System.Nullable<bool> Aprove_Atasan
		{
			get
			{
				return this._Aprove_Atasan;
			}
			set
			{
				if ((this._Aprove_Atasan != value))
				{
					this._Aprove_Atasan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_by", DbType="VarChar(50)")]
		public string Aprove_by
		{
			get
			{
				return this._Aprove_by;
			}
			set
			{
				if ((this._Aprove_by != value))
				{
					this._Aprove_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_tanggal", DbType="DateTime")]
		public System.Nullable<System.DateTime> Aprove_tanggal
		{
			get
			{
				return this._Aprove_tanggal;
			}
			set
			{
				if ((this._Aprove_tanggal != value))
				{
					this._Aprove_tanggal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_HC", DbType="Bit")]
		public System.Nullable<bool> Aprove_HC
		{
			get
			{
				return this._Aprove_HC;
			}
			set
			{
				if ((this._Aprove_HC != value))
				{
					this._Aprove_HC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_HC_by", DbType="VarChar(50)")]
		public string Aprove_HC_by
		{
			get
			{
				return this._Aprove_HC_by;
			}
			set
			{
				if ((this._Aprove_HC_by != value))
				{
					this._Aprove_HC_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprove_HC_tanggal", DbType="DateTime")]
		public System.Nullable<System.DateTime> Aprove_HC_tanggal
		{
			get
			{
				return this._Aprove_HC_tanggal;
			}
			set
			{
				if ((this._Aprove_HC_tanggal != value))
				{
					this._Aprove_HC_tanggal = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
