#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrgaEnhance.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_TAMARA")]
	public partial class LtsGesitDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_T_TRAVEL_REQUEST(TBL_T_TRAVEL_REQUEST instance);
    partial void UpdateTBL_T_TRAVEL_REQUEST(TBL_T_TRAVEL_REQUEST instance);
    partial void DeleteTBL_T_TRAVEL_REQUEST(TBL_T_TRAVEL_REQUEST instance);
    #endregion
		
		public LtsGesitDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_TAMARAConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LtsGesitDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LtsGesitDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LtsGesitDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LtsGesitDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VW_TRAVEL_REQUEST> VW_TRAVEL_REQUESTs
		{
			get
			{
				return this.GetTable<VW_TRAVEL_REQUEST>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_TRAVEL_REQUEST> TBL_T_TRAVEL_REQUESTs
		{
			get
			{
				return this.GetTable<TBL_T_TRAVEL_REQUEST>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_TRAVEL_REQUEST")]
	public partial class VW_TRAVEL_REQUEST
	{
		
		private int _ID;
		
		private string _NOMOR;
		
		private string _NRP;
		
		private string _NAMA;
		
		private string _DEPARTEMEN;
		
		private string _JABATAN;
		
		private string _UMUR;
		
		private string _JAM_BERANGKAT;
		
		private string _DARI;
		
		private string _TUJUAN;
		
		private string _KETERANGAN;
		
		private string _STATUS_KELUARGA;
		
		private string _NO_HP;
		
		private System.Nullable<bool> _AKOMODASI_TRANSPORT;
		
		private System.Nullable<bool> _AKOMODASI_MESS;
		
		private int _AKOMODASI_TIKET;
		
		private System.Nullable<int> _IDFLIGHT;
		
		private string _DIBUAT_OLEH;
		
		private System.Nullable<System.DateTime> _TANGGAL_TRAVEL;
		
		private System.Nullable<System.DateTime> _TANGGAL_KEMBALI;
		
		private string _KEPERLUAN;
		
		private string _STATUS;
		
		private string _STATUS_DESC;
		
		private string _AWALST;
		
		private string _AKHIRST;
		
		private System.Nullable<bool> _SARANA_REGULER;
		
		private string _SARANA_REGULER_DESC;
		
		private int _PRIORITAS;
		
		public VW_TRAVEL_REQUEST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMOR", DbType="VarChar(25)")]
		public string NOMOR
		{
			get
			{
				return this._NOMOR;
			}
			set
			{
				if ((this._NOMOR != value))
				{
					this._NOMOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(15)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(150)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this._NAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTEMEN", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string DEPARTEMEN
		{
			get
			{
				return this._DEPARTEMEN;
			}
			set
			{
				if ((this._DEPARTEMEN != value))
				{
					this._DEPARTEMEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JABATAN", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string JABATAN
		{
			get
			{
				return this._JABATAN;
			}
			set
			{
				if ((this._JABATAN != value))
				{
					this._JABATAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UMUR", DbType="VarChar(10)")]
		public string UMUR
		{
			get
			{
				return this._UMUR;
			}
			set
			{
				if ((this._UMUR != value))
				{
					this._UMUR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JAM_BERANGKAT", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string JAM_BERANGKAT
		{
			get
			{
				return this._JAM_BERANGKAT;
			}
			set
			{
				if ((this._JAM_BERANGKAT != value))
				{
					this._JAM_BERANGKAT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DARI", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string DARI
		{
			get
			{
				return this._DARI;
			}
			set
			{
				if ((this._DARI != value))
				{
					this._DARI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUJUAN", DbType="VarChar(150)")]
		public string TUJUAN
		{
			get
			{
				return this._TUJUAN;
			}
			set
			{
				if ((this._TUJUAN != value))
				{
					this._TUJUAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KETERANGAN", DbType="VarChar(200)")]
		public string KETERANGAN
		{
			get
			{
				return this._KETERANGAN;
			}
			set
			{
				if ((this._KETERANGAN != value))
				{
					this._KETERANGAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_KELUARGA", DbType="VarChar(10)")]
		public string STATUS_KELUARGA
		{
			get
			{
				return this._STATUS_KELUARGA;
			}
			set
			{
				if ((this._STATUS_KELUARGA != value))
				{
					this._STATUS_KELUARGA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_HP", DbType="VarChar(15)")]
		public string NO_HP
		{
			get
			{
				return this._NO_HP;
			}
			set
			{
				if ((this._NO_HP != value))
				{
					this._NO_HP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKOMODASI_TRANSPORT", DbType="Bit")]
		public System.Nullable<bool> AKOMODASI_TRANSPORT
		{
			get
			{
				return this._AKOMODASI_TRANSPORT;
			}
			set
			{
				if ((this._AKOMODASI_TRANSPORT != value))
				{
					this._AKOMODASI_TRANSPORT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKOMODASI_MESS", DbType="Bit")]
		public System.Nullable<bool> AKOMODASI_MESS
		{
			get
			{
				return this._AKOMODASI_MESS;
			}
			set
			{
				if ((this._AKOMODASI_MESS != value))
				{
					this._AKOMODASI_MESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKOMODASI_TIKET", DbType="Int NOT NULL")]
		public int AKOMODASI_TIKET
		{
			get
			{
				return this._AKOMODASI_TIKET;
			}
			set
			{
				if ((this._AKOMODASI_TIKET != value))
				{
					this._AKOMODASI_TIKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDFLIGHT", DbType="Int")]
		public System.Nullable<int> IDFLIGHT
		{
			get
			{
				return this._IDFLIGHT;
			}
			set
			{
				if ((this._IDFLIGHT != value))
				{
					this._IDFLIGHT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIBUAT_OLEH", DbType="VarChar(100)")]
		public string DIBUAT_OLEH
		{
			get
			{
				return this._DIBUAT_OLEH;
			}
			set
			{
				if ((this._DIBUAT_OLEH != value))
				{
					this._DIBUAT_OLEH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TANGGAL_TRAVEL", DbType="DateTime")]
		public System.Nullable<System.DateTime> TANGGAL_TRAVEL
		{
			get
			{
				return this._TANGGAL_TRAVEL;
			}
			set
			{
				if ((this._TANGGAL_TRAVEL != value))
				{
					this._TANGGAL_TRAVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TANGGAL_KEMBALI", DbType="DateTime")]
		public System.Nullable<System.DateTime> TANGGAL_KEMBALI
		{
			get
			{
				return this._TANGGAL_KEMBALI;
			}
			set
			{
				if ((this._TANGGAL_KEMBALI != value))
				{
					this._TANGGAL_KEMBALI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEPERLUAN", DbType="VarChar(10)")]
		public string KEPERLUAN
		{
			get
			{
				return this._KEPERLUAN;
			}
			set
			{
				if ((this._KEPERLUAN != value))
				{
					this._KEPERLUAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(3)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_DESC", DbType="VarChar(50)")]
		public string STATUS_DESC
		{
			get
			{
				return this._STATUS_DESC;
			}
			set
			{
				if ((this._STATUS_DESC != value))
				{
					this._STATUS_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWALST", DbType="VarChar(8)")]
		public string AWALST
		{
			get
			{
				return this._AWALST;
			}
			set
			{
				if ((this._AWALST != value))
				{
					this._AWALST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKHIRST", DbType="VarChar(8)")]
		public string AKHIRST
		{
			get
			{
				return this._AKHIRST;
			}
			set
			{
				if ((this._AKHIRST != value))
				{
					this._AKHIRST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SARANA_REGULER", DbType="Bit")]
		public System.Nullable<bool> SARANA_REGULER
		{
			get
			{
				return this._SARANA_REGULER;
			}
			set
			{
				if ((this._SARANA_REGULER != value))
				{
					this._SARANA_REGULER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SARANA_REGULER_DESC", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string SARANA_REGULER_DESC
		{
			get
			{
				return this._SARANA_REGULER_DESC;
			}
			set
			{
				if ((this._SARANA_REGULER_DESC != value))
				{
					this._SARANA_REGULER_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIORITAS", DbType="Int NOT NULL")]
		public int PRIORITAS
		{
			get
			{
				return this._PRIORITAS;
			}
			set
			{
				if ((this._PRIORITAS != value))
				{
					this._PRIORITAS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_TRAVEL_REQUEST")]
	public partial class TBL_T_TRAVEL_REQUEST : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_REQUEST;
		
		private string _NOMOR;
		
		private string _NRP;
		
		private string _NAMA;
		
		private string _STATUS_KELUARGA;
		
		private string _UMUR;
		
		private string _NO_HP;
		
		private string _KEPERLUAN;
		
		private string _AREA;
		
		private string _DARI;
		
		private string _TUJUAN;
		
		private System.Nullable<System.DateTime> _TANGGAL;
		
		private string _JAM_BERANGKAT;
		
		private System.Nullable<System.DateTime> _TANGGAL_KEMBALI;
		
		private string _DARI_KEMBALI;
		
		private string _TUJUAN_KEMBALI;
		
		private string _JAM_KEMBALI;
		
		private string _REMARK;
		
		private System.Nullable<bool> _AKOMODASI_TRANSPORT;
		
		private System.Nullable<bool> _AKOMODASI_MESS;
		
		private System.Nullable<bool> _SARANA_REGULER;
		
		private System.Nullable<int> _IDFLIGHT;
		
		private string _STATUS;
		
		private string _INSERTBY;
		
		private System.Nullable<System.DateTime> _INSERTDATE;
		
		private string _UPDATEBY;
		
		private System.Nullable<System.DateTime> _LASTUPDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_REQUESTChanging(int value);
    partial void OnID_REQUESTChanged();
    partial void OnNOMORChanging(string value);
    partial void OnNOMORChanged();
    partial void OnNRPChanging(string value);
    partial void OnNRPChanged();
    partial void OnNAMAChanging(string value);
    partial void OnNAMAChanged();
    partial void OnSTATUS_KELUARGAChanging(string value);
    partial void OnSTATUS_KELUARGAChanged();
    partial void OnUMURChanging(string value);
    partial void OnUMURChanged();
    partial void OnNO_HPChanging(string value);
    partial void OnNO_HPChanged();
    partial void OnKEPERLUANChanging(string value);
    partial void OnKEPERLUANChanged();
    partial void OnAREAChanging(string value);
    partial void OnAREAChanged();
    partial void OnDARIChanging(string value);
    partial void OnDARIChanged();
    partial void OnTUJUANChanging(string value);
    partial void OnTUJUANChanged();
    partial void OnTANGGALChanging(System.Nullable<System.DateTime> value);
    partial void OnTANGGALChanged();
    partial void OnJAM_BERANGKATChanging(string value);
    partial void OnJAM_BERANGKATChanged();
    partial void OnTANGGAL_KEMBALIChanging(System.Nullable<System.DateTime> value);
    partial void OnTANGGAL_KEMBALIChanged();
    partial void OnDARI_KEMBALIChanging(string value);
    partial void OnDARI_KEMBALIChanged();
    partial void OnTUJUAN_KEMBALIChanging(string value);
    partial void OnTUJUAN_KEMBALIChanged();
    partial void OnJAM_KEMBALIChanging(string value);
    partial void OnJAM_KEMBALIChanged();
    partial void OnREMARKChanging(string value);
    partial void OnREMARKChanged();
    partial void OnAKOMODASI_TRANSPORTChanging(System.Nullable<bool> value);
    partial void OnAKOMODASI_TRANSPORTChanged();
    partial void OnAKOMODASI_MESSChanging(System.Nullable<bool> value);
    partial void OnAKOMODASI_MESSChanged();
    partial void OnSARANA_REGULERChanging(System.Nullable<bool> value);
    partial void OnSARANA_REGULERChanged();
    partial void OnIDFLIGHTChanging(System.Nullable<int> value);
    partial void OnIDFLIGHTChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    partial void OnINSERTBYChanging(string value);
    partial void OnINSERTBYChanged();
    partial void OnINSERTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnINSERTDATEChanged();
    partial void OnUPDATEBYChanging(string value);
    partial void OnUPDATEBYChanged();
    partial void OnLASTUPDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnLASTUPDATEChanged();
    #endregion
		
		public TBL_T_TRAVEL_REQUEST()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_REQUEST", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_REQUEST
		{
			get
			{
				return this._ID_REQUEST;
			}
			set
			{
				if ((this._ID_REQUEST != value))
				{
					this.OnID_REQUESTChanging(value);
					this.SendPropertyChanging();
					this._ID_REQUEST = value;
					this.SendPropertyChanged("ID_REQUEST");
					this.OnID_REQUESTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMOR", DbType="VarChar(25)")]
		public string NOMOR
		{
			get
			{
				return this._NOMOR;
			}
			set
			{
				if ((this._NOMOR != value))
				{
					this.OnNOMORChanging(value);
					this.SendPropertyChanging();
					this._NOMOR = value;
					this.SendPropertyChanged("NOMOR");
					this.OnNOMORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(15)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this.OnNRPChanging(value);
					this.SendPropertyChanging();
					this._NRP = value;
					this.SendPropertyChanged("NRP");
					this.OnNRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(150)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this.OnNAMAChanging(value);
					this.SendPropertyChanging();
					this._NAMA = value;
					this.SendPropertyChanged("NAMA");
					this.OnNAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_KELUARGA", DbType="VarChar(10)")]
		public string STATUS_KELUARGA
		{
			get
			{
				return this._STATUS_KELUARGA;
			}
			set
			{
				if ((this._STATUS_KELUARGA != value))
				{
					this.OnSTATUS_KELUARGAChanging(value);
					this.SendPropertyChanging();
					this._STATUS_KELUARGA = value;
					this.SendPropertyChanged("STATUS_KELUARGA");
					this.OnSTATUS_KELUARGAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UMUR", DbType="VarChar(10)")]
		public string UMUR
		{
			get
			{
				return this._UMUR;
			}
			set
			{
				if ((this._UMUR != value))
				{
					this.OnUMURChanging(value);
					this.SendPropertyChanging();
					this._UMUR = value;
					this.SendPropertyChanged("UMUR");
					this.OnUMURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_HP", DbType="VarChar(15)")]
		public string NO_HP
		{
			get
			{
				return this._NO_HP;
			}
			set
			{
				if ((this._NO_HP != value))
				{
					this.OnNO_HPChanging(value);
					this.SendPropertyChanging();
					this._NO_HP = value;
					this.SendPropertyChanged("NO_HP");
					this.OnNO_HPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEPERLUAN", DbType="VarChar(10)")]
		public string KEPERLUAN
		{
			get
			{
				return this._KEPERLUAN;
			}
			set
			{
				if ((this._KEPERLUAN != value))
				{
					this.OnKEPERLUANChanging(value);
					this.SendPropertyChanging();
					this._KEPERLUAN = value;
					this.SendPropertyChanged("KEPERLUAN");
					this.OnKEPERLUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA", DbType="VarChar(10)")]
		public string AREA
		{
			get
			{
				return this._AREA;
			}
			set
			{
				if ((this._AREA != value))
				{
					this.OnAREAChanging(value);
					this.SendPropertyChanging();
					this._AREA = value;
					this.SendPropertyChanged("AREA");
					this.OnAREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DARI", DbType="VarChar(150)")]
		public string DARI
		{
			get
			{
				return this._DARI;
			}
			set
			{
				if ((this._DARI != value))
				{
					this.OnDARIChanging(value);
					this.SendPropertyChanging();
					this._DARI = value;
					this.SendPropertyChanged("DARI");
					this.OnDARIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUJUAN", DbType="VarChar(150)")]
		public string TUJUAN
		{
			get
			{
				return this._TUJUAN;
			}
			set
			{
				if ((this._TUJUAN != value))
				{
					this.OnTUJUANChanging(value);
					this.SendPropertyChanging();
					this._TUJUAN = value;
					this.SendPropertyChanged("TUJUAN");
					this.OnTUJUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TANGGAL", DbType="Date")]
		public System.Nullable<System.DateTime> TANGGAL
		{
			get
			{
				return this._TANGGAL;
			}
			set
			{
				if ((this._TANGGAL != value))
				{
					this.OnTANGGALChanging(value);
					this.SendPropertyChanging();
					this._TANGGAL = value;
					this.SendPropertyChanged("TANGGAL");
					this.OnTANGGALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JAM_BERANGKAT", DbType="VarChar(5)")]
		public string JAM_BERANGKAT
		{
			get
			{
				return this._JAM_BERANGKAT;
			}
			set
			{
				if ((this._JAM_BERANGKAT != value))
				{
					this.OnJAM_BERANGKATChanging(value);
					this.SendPropertyChanging();
					this._JAM_BERANGKAT = value;
					this.SendPropertyChanged("JAM_BERANGKAT");
					this.OnJAM_BERANGKATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TANGGAL_KEMBALI", DbType="Date")]
		public System.Nullable<System.DateTime> TANGGAL_KEMBALI
		{
			get
			{
				return this._TANGGAL_KEMBALI;
			}
			set
			{
				if ((this._TANGGAL_KEMBALI != value))
				{
					this.OnTANGGAL_KEMBALIChanging(value);
					this.SendPropertyChanging();
					this._TANGGAL_KEMBALI = value;
					this.SendPropertyChanged("TANGGAL_KEMBALI");
					this.OnTANGGAL_KEMBALIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DARI_KEMBALI", DbType="VarChar(150)")]
		public string DARI_KEMBALI
		{
			get
			{
				return this._DARI_KEMBALI;
			}
			set
			{
				if ((this._DARI_KEMBALI != value))
				{
					this.OnDARI_KEMBALIChanging(value);
					this.SendPropertyChanging();
					this._DARI_KEMBALI = value;
					this.SendPropertyChanged("DARI_KEMBALI");
					this.OnDARI_KEMBALIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUJUAN_KEMBALI", DbType="VarChar(150)")]
		public string TUJUAN_KEMBALI
		{
			get
			{
				return this._TUJUAN_KEMBALI;
			}
			set
			{
				if ((this._TUJUAN_KEMBALI != value))
				{
					this.OnTUJUAN_KEMBALIChanging(value);
					this.SendPropertyChanging();
					this._TUJUAN_KEMBALI = value;
					this.SendPropertyChanged("TUJUAN_KEMBALI");
					this.OnTUJUAN_KEMBALIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JAM_KEMBALI", DbType="VarChar(5)")]
		public string JAM_KEMBALI
		{
			get
			{
				return this._JAM_KEMBALI;
			}
			set
			{
				if ((this._JAM_KEMBALI != value))
				{
					this.OnJAM_KEMBALIChanging(value);
					this.SendPropertyChanging();
					this._JAM_KEMBALI = value;
					this.SendPropertyChanged("JAM_KEMBALI");
					this.OnJAM_KEMBALIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARK", DbType="VarChar(200)")]
		public string REMARK
		{
			get
			{
				return this._REMARK;
			}
			set
			{
				if ((this._REMARK != value))
				{
					this.OnREMARKChanging(value);
					this.SendPropertyChanging();
					this._REMARK = value;
					this.SendPropertyChanged("REMARK");
					this.OnREMARKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKOMODASI_TRANSPORT", DbType="Bit")]
		public System.Nullable<bool> AKOMODASI_TRANSPORT
		{
			get
			{
				return this._AKOMODASI_TRANSPORT;
			}
			set
			{
				if ((this._AKOMODASI_TRANSPORT != value))
				{
					this.OnAKOMODASI_TRANSPORTChanging(value);
					this.SendPropertyChanging();
					this._AKOMODASI_TRANSPORT = value;
					this.SendPropertyChanged("AKOMODASI_TRANSPORT");
					this.OnAKOMODASI_TRANSPORTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKOMODASI_MESS", DbType="Bit")]
		public System.Nullable<bool> AKOMODASI_MESS
		{
			get
			{
				return this._AKOMODASI_MESS;
			}
			set
			{
				if ((this._AKOMODASI_MESS != value))
				{
					this.OnAKOMODASI_MESSChanging(value);
					this.SendPropertyChanging();
					this._AKOMODASI_MESS = value;
					this.SendPropertyChanged("AKOMODASI_MESS");
					this.OnAKOMODASI_MESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SARANA_REGULER", DbType="Bit")]
		public System.Nullable<bool> SARANA_REGULER
		{
			get
			{
				return this._SARANA_REGULER;
			}
			set
			{
				if ((this._SARANA_REGULER != value))
				{
					this.OnSARANA_REGULERChanging(value);
					this.SendPropertyChanging();
					this._SARANA_REGULER = value;
					this.SendPropertyChanged("SARANA_REGULER");
					this.OnSARANA_REGULERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDFLIGHT", DbType="Int")]
		public System.Nullable<int> IDFLIGHT
		{
			get
			{
				return this._IDFLIGHT;
			}
			set
			{
				if ((this._IDFLIGHT != value))
				{
					this.OnIDFLIGHTChanging(value);
					this.SendPropertyChanging();
					this._IDFLIGHT = value;
					this.SendPropertyChanged("IDFLIGHT");
					this.OnIDFLIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(3)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSERTBY", DbType="VarChar(10)")]
		public string INSERTBY
		{
			get
			{
				return this._INSERTBY;
			}
			set
			{
				if ((this._INSERTBY != value))
				{
					this.OnINSERTBYChanging(value);
					this.SendPropertyChanging();
					this._INSERTBY = value;
					this.SendPropertyChanged("INSERTBY");
					this.OnINSERTBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSERTDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> INSERTDATE
		{
			get
			{
				return this._INSERTDATE;
			}
			set
			{
				if ((this._INSERTDATE != value))
				{
					this.OnINSERTDATEChanging(value);
					this.SendPropertyChanging();
					this._INSERTDATE = value;
					this.SendPropertyChanged("INSERTDATE");
					this.OnINSERTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATEBY", DbType="VarChar(10)")]
		public string UPDATEBY
		{
			get
			{
				return this._UPDATEBY;
			}
			set
			{
				if ((this._UPDATEBY != value))
				{
					this.OnUPDATEBYChanging(value);
					this.SendPropertyChanging();
					this._UPDATEBY = value;
					this.SendPropertyChanged("UPDATEBY");
					this.OnUPDATEBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTUPDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> LASTUPDATE
		{
			get
			{
				return this._LASTUPDATE;
			}
			set
			{
				if ((this._LASTUPDATE != value))
				{
					this.OnLASTUPDATEChanging(value);
					this.SendPropertyChanging();
					this._LASTUPDATE = value;
					this.SendPropertyChanged("LASTUPDATE");
					this.OnLASTUPDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
